# Generated by Django 3.2.16 on 2023-01-11 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('twoG', models.BooleanField()),
                ('threeG', models.BooleanField()),
                ('fourG', models.BooleanField()),
            ],
            options={
                'unique_together': {('twoG', 'threeG', 'fourG')},
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkOperatorCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkApp.city')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkApp.network')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkApp.operator')),
            ],
            options={
                'unique_together': {('city', 'operator', 'network')},
            },
        ),
    ]
